# Generated by Django 3.2.4 on 2022-11-27 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('taste', models.CharField(max_length=128)),
                ('color', models.CharField(max_length=128)),
                ('price', models.FloatField(max_length=128)),
            ],
        ),
    ]
