# Generated by Django 3.2.4 on 2022-11-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('author', models.CharField(max_length=300)),
                ('pages', models.IntegerField(max_length=300)),
                ('price', models.FloatField(max_length=300)),
            ],
        ),
    ]
